references:
    basepath: "path_to_references_data"
    provider: "reference_provider"
    release: "reference_release"

genome_fasta: "_genome_fasta"
repository:
  gatkdoc_plugin: "https://bitbucket.org/massiddaMT/gatkdoc_plugin.git"

paths:
  to_gatk: "path_to_software-gatk3.7"
  to_tmp: "path_to_tmp_dir"


rules:
    depth_coverage:
        params: "-ct 15 -ct 20 -ct 30 --omitDepthOutputAtEachBase --omitIntervalStatistics --omitLocusTable --countType COUNT_READS "
    bbmap:
        params: "binsize=1000000 -Xmx8g "
    multiqc:
        arguments: ""
    qualimap:
        params: "-c -nw 400 -nr 1000 -sd -sdmode 0 --java-mem-size=20G"
        outformat: "PDF:HTML "
samples: my.bam.list