references:
    basepath: "/ELS/els9/users/biosciences/references"
    provider: "ncbi"
    release: "Ovis_aries_4.0"

genome_fasta: "oar_ref_Oar_v4.0_fixChr.fa"
repository:
  gatkdoc_plugin: "https://bitbucket.org/massiddaMT/gatkdoc_plugin.git"

paths:
  to_gatk: "/ELS/els9/users/biosciences/software/gatk-3.7"
  to_tmp: "/tmp"
  to_sample: "reads/recalibrated"
  to_bbmap_out: "cov/bbmap/"
  to_gatkdoc_out: "cov"

rules:
    depth_coverage:
        params: "-ct 15 -ct 20 -ct 30 --omitDepthOutputAtEachBase --omitIntervalStatistics --omitLocusTable --countType COUNT_READS "
    bbmap:
        params: "binsize=1000000 -Xmx8g "
    multiqc:
        arguments: ""
    qualimap:
        params: "-c -nw 400 -nr 1000 -sd -sdmode 0 --java-mem-size=20G"
        outformat: "PDF:HTML "
samples: my.bam.list